// This file was auto-generated by Fern from our API Definition.

package client

import (
	core "github.com/intrinsic-org/intrinsic-go/core"
	detections "github.com/intrinsic-org/intrinsic-go/detections"
	events "github.com/intrinsic-org/intrinsic-go/events"
	eventtypes "github.com/intrinsic-org/intrinsic-go/eventtypes"
	option "github.com/intrinsic-org/intrinsic-go/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *core.Caller
	header  http.Header

	Detections *detections.Client
	Events     *events.Client
	EventTypes *eventtypes.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: core.NewCaller(
			&core.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:     options.ToHeader(),
		Detections: detections.NewClient(opts...),
		Events:     events.NewClient(opts...),
		EventTypes: eventtypes.NewClient(opts...),
	}
}
